import keyboard

import time
#updaate MB120 powering-start at last output
keyboard.press_and_release('alt+tab')
time.sleep(2)
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('.74')
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('.67')
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('.66')
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('.63')
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('.6')
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('.54')
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('45')
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('55')
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('60')
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('70')
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('80')
keyboard.press_and_release('tab')
time.sleep(.1)
keyboard.write('90')